language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq librecode-dev
  - sudo pip install cpp-coveralls --use-mirrors
script: 
  - ./configure --with-gcov && make && make test
after_success:
  - coveralls
